cr_backend_admin:
    resource:   "@CreditUnionBackendBundle/Controller/AdminController.php"
    type:       annotation
    
cr_backend_user:
    resource:   "@CreditUnionBackendBundle/Controller/MyUserController.php"
    type:       annotation
    
cr_backend_branch:
    resource:   "@CreditUnionBackendBundle/Controller/BranchController.php"
    type:       annotation
    
cr_backend_importformat:
    resource:   "@CreditUnionBackendBundle/Controller/ImportFormatController.php"
    type:       annotation